name: SyncToS3

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log Environment Variables
        run: |
          echo "AWS_REGION: $AWS_REGION"
          echo "AWS_S3_BUCKET: $AWS_S3_BUCKET"
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::262996808057:role/github-s3-role  # Replace with your IAM Role ARN
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@master  # Alternative working action
        with:
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          region: ${{ secrets.AWS_REGION }}
          src: './public'
          overwrite: true
          delete-removed: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}