name: SyncToS3

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Attempt AWS Role Assumption with Retry
        id: configure-aws
        with:
          role-to-assume: arn:aws:iam::262996808057:role/github-s3-role
          aws-region: ${{ secrets.AWS_REGION }}
          retries: 3

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          region: ${{ secrets.AWS_REGION }}
          src: './public'
          overwrite: true
          delete-removed: true