name: SyncToS3

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::262996808057:role/github-s3-role
          aws-region: ${{ secrets.AWS_REGION }}
          retry-max-attempts: 3
          output-credentials: true
          unset-current-credentials: true

      - name: Debug AWS Variables
        run: |
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN"

      - name: Sync Only `index.html` and `static/*` to S3
        run: |
          aws s3 cp ./index.html s3://${{ secrets.AWS_S3_BUCKET }}/
          aws s3 sync ./static/ s3://${{ secrets.AWS_S3_BUCKET }}/static/