name: SyncToS3

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::262996808057:role/github-s3-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@v2
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*'
        env:
          SOURCE_DIR: './public'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}